steps:

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/will-weiss/hotspot-notification-server']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']

- name: 'gcr.io/cloud-builders/kubectl'
- args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'