version: "3.2"

services:
  hotspot-notification-server:
    networks:
      default:
        aliases:
          - hotspot-notification-server
    build:
      context: .
    env_file:
      - .env_default
      - .env
    command: npm run dev
    volumes:
      - ./src:/usr/hotspot-notification-server/src
    ports:
      - "5004:5004"
